#!/usr/bin/env python3
"""Post-investigation action for Dependabot security alerts.

Reads .blender-alert-verdict.json and takes the appropriate action:

  not-affected + existing Dependabot PR -> no-op (existing pipeline handles it)
  not-affected + no PR                 -> open a bump PR
  affected                             -> create advisory with private fork

Environment variables:
  GH_TOKEN              -- GitHub token (required)
  REPO                  -- Target repo, e.g. mozilla/fx-private-relay (required)
  ALERT_NUMBER          -- Dependabot alert number (required)
  ALERT_PACKAGE         -- Package name (required)
  ALERT_ECOSYSTEM       -- Ecosystem, e.g. npm or pip (required)
  ALERT_PATCHED_VERSION -- Version to bump to (required for bump PRs)
  DRY_RUN               -- Set to "true" to skip mutations (default: false)
"""

from __future__ import annotations

import json
import os
import sys
import time

from github import Auth, Github

VERDICT_FILE = ".blender-alert-verdict.json"
REQUIRED_KEYS = {
    "affected",
    "confidence",
    "reason",
    "vulnerable_paths",
    "recommended_action",
}


def load_verdict() -> dict | None:
    """Load and validate the alert verdict file."""
    if not os.path.exists(VERDICT_FILE):
        print(f"No verdict file at {VERDICT_FILE}.")
        return None

    with open(VERDICT_FILE) as f:
        verdict = json.load(f)

    missing = REQUIRED_KEYS - set(verdict.keys())
    if missing:
        print(f"Verdict missing keys: {missing}")
        return None

    return verdict


def find_existing_pr(repo, package_name: str) -> bool:
    """Check if an open Dependabot PR already bumps this package."""
    for pr in repo.get_pulls(state="open"):
        if pr.user.login != "dependabot[bot]":
            continue
        if package_name.lower() in pr.title.lower():
            print(f"  Existing PR #{pr.number}: {pr.title}")
            return True
    return False


def open_bump_pr(
    repo,
    alert_number: int,
    package_name: str,
    patched_version: str,
    ecosystem: str,
    dry_run: bool,
) -> None:
    """Create a branch and PR to bump the package to the patched version.

    This creates a minimal PR that updates the dependency specification.
    The actual file to modify depends on the ecosystem.
    """
    branch_name = f"blender/security/{alert_number}-{package_name}"
    default_branch = repo.default_branch
    title = f"fix(security): bump {package_name} to {patched_version}"
    body = (
        f"Bumps **{package_name}** to `{patched_version}` to resolve "
        f"Dependabot alert #{alert_number}.\n\n"
        f"BLEnder determined this vulnerability does not affect the "
        f"codebase, but the dependency should still be updated.\n\n"
        f"---\n"
        f"Generated by [BLEnder](https://github.com/mozilla/blender)."
    )

    if dry_run:
        print(f"  DRY_RUN: would create branch {branch_name}")
        print(f"  DRY_RUN: would open PR: {title}")
        return

    # Check if branch already exists
    try:
        repo.get_branch(branch_name)
        print(f"  Branch {branch_name} already exists, skipping.")
        return
    except Exception:
        pass

    # Create branch from default branch HEAD
    ref = repo.get_git_ref(f"heads/{default_branch}")
    repo.create_git_ref(f"refs/heads/{branch_name}", ref.object.sha)
    print(f"  Created branch {branch_name}")

    # Open PR (no file changes yet — Dependabot or CI will handle the bump)
    pr = repo.create_pull(
        title=title,
        body=body,
        head=branch_name,
        base=default_branch,
    )
    print(f"  Opened PR #{pr.number}: {title}")


def create_advisory_and_fork(
    repo,
    alert_number: int,
    package_name: str,
    dry_run: bool,
) -> tuple[str, str]:
    """Create a security advisory with a private fork.

    Returns (advisory_ghsa_id, fork_full_name) on success.
    """
    summary = f"Dependency security update for {package_name}"
    description = (
        f"Automated security update for Dependabot alert #{alert_number}. "
        f"See the advisory for details."
    )

    if dry_run:
        print(f"  DRY_RUN: would create advisory: {summary}")
        return ("", "")

    # Create advisory via raw API (PyGithub has no built-in method)
    url = f"/repos/{repo.full_name}/security-advisories"
    payload = {
        "summary": summary,
        "description": description,
        "severity": "low",
        "start_private_fork": True,
    }
    try:
        _, data = repo._requester.requestJsonAndCheck("POST", url, input=payload)
    except Exception as e:
        # Duplicate advisory returns 422
        error_str = str(e)
        if "422" in error_str or "already exists" in error_str.lower():
            print(f"  Advisory already exists for alert #{alert_number}, skipping.")
            return ("", "")
        raise

    ghsa_id = data.get("ghsa_id", "")
    print(f"  Created advisory {ghsa_id}")

    # Poll for private fork readiness (up to 5 minutes)
    fork_full_name = ""
    advisory_url = f"/repos/{repo.full_name}/security-advisories/{ghsa_id}"
    for attempt in range(10):
        time.sleep(min(30, 5 * (2**attempt)))
        _, advisory_data = repo._requester.requestJsonAndCheck("GET", advisory_url)
        forks = advisory_data.get("vulnerabilities", [])
        if forks:
            # The fork repo is in the advisory's fork field
            fork_info = advisory_data.get("private_fork", {})
            if fork_info:
                fork_full_name = fork_info.get("full_name", "")
                break
        # Also check top-level
        if advisory_data.get("private_fork"):
            fork_full_name = advisory_data["private_fork"].get("full_name", "")
            if fork_full_name:
                break

    if fork_full_name:
        print(f"  Private fork ready: {fork_full_name}")
    else:
        print("  Private fork not ready after polling. Remediate job may fail.")

    return (ghsa_id, fork_full_name)


def main() -> None:
    token = os.environ.get("GH_TOKEN", "")
    repo_name = os.environ.get("REPO", "")
    alert_number = int(os.environ.get("ALERT_NUMBER", "0"))
    package_name = os.environ.get("ALERT_PACKAGE", "unknown")
    ecosystem = os.environ.get("ALERT_ECOSYSTEM", "unknown")
    patched_version = os.environ.get("ALERT_PATCHED_VERSION", "")
    dry_run = os.environ.get("DRY_RUN", "false").lower() in ("true", "1", "yes")

    if not token or not repo_name:
        print("Error: GH_TOKEN and REPO are required.")
        sys.exit(1)

    if alert_number == 0:
        print("Error: ALERT_NUMBER is required.")
        sys.exit(1)

    g = Github(auth=Auth.Token(token))
    repo = g.get_repo(repo_name)

    verdict = load_verdict()
    if verdict is None:
        print("No valid verdict. Defaulting to no-op.")
        write_output("action", "noop")
        return

    affected = verdict.get("affected", False)
    recommended = verdict.get("recommended_action", "bump_pr")
    print(f"Verdict: affected={affected}, recommended={recommended}")
    print(f"  Reason: {verdict.get('reason', '(none)')}")

    if not affected:
        # Check for existing Dependabot PR
        has_pr = find_existing_pr(repo, package_name)

        if has_pr or recommended == "existing_pr":
            print("  Not affected + existing PR. No action needed.")
            write_output("action", "noop")
        else:
            print("  Not affected + no PR. Opening bump PR.")
            open_bump_pr(
                repo,
                alert_number,
                package_name,
                patched_version,
                ecosystem,
                dry_run,
            )
            write_output("action", "bump_pr")
    else:
        print("  Affected. Creating advisory and private fork.")
        ghsa_id, fork_repo = create_advisory_and_fork(
            repo,
            alert_number,
            package_name,
            dry_run,
        )
        write_output("action", "private_fork")
        write_output("advisory_ghsa_id", ghsa_id)
        write_output("fork_repo", fork_repo)


def write_output(key: str, value: str) -> None:
    """Write a key=value pair to $GITHUB_OUTPUT."""
    output_file = os.environ.get("GITHUB_OUTPUT")
    if output_file:
        with open(output_file, "a") as f:
            f.write(f"{key}={value}\n")
    print(f"  output: {key}={value}")


if __name__ == "__main__":
    main()
