#!/usr/bin/env python3
"""Post-investigation action for Dependabot security alerts.

Reads .blender-alert-verdict.json and takes the appropriate action:

  not-affected + dismiss enabled        -> dismiss the alert via API
  not-affected + existing Dependabot PR -> no-op (existing pipeline handles it)
  not-affected + no PR                  -> open a bump PR
  affected                              -> create advisory with private fork

Each run posts a row to a tracking issue on the target repo so the
owner can see all results in one place.

Environment variables:
  GH_TOKEN              -- GitHub token (required)
  REPO                  -- Target repo, e.g. mozilla/fx-private-relay (required)
  ALERT_NUMBER          -- Dependabot alert number (required)
  ALERT_PACKAGE         -- Package name (required)
  ALERT_ECOSYSTEM       -- Ecosystem, e.g. npm or pip (required)
  ALERT_SEVERITY        -- Alert severity (optional, for summary report)
  ALERT_PATCHED_VERSION -- Version to bump to (required for bump PRs)
  DRY_RUN               -- Set to "true" to skip mutations (default: false)
  DISMISS_NOT_AFFECTED  -- Set to "true" to dismiss non-affected alerts
"""

from __future__ import annotations

import json
import os
import sys
import time

from github import Auth, Github

VERDICT_FILE = ".blender-alert-verdict.json"
REQUIRED_KEYS = {
    "affected",
    "confidence",
    "reason",
    "vulnerable_paths",
    "recommended_action",
}


def load_verdict() -> dict | None:
    """Load and validate the alert verdict file."""
    if not os.path.exists(VERDICT_FILE):
        print(f"No verdict file at {VERDICT_FILE}.")
        return None

    with open(VERDICT_FILE) as f:
        verdict = json.load(f)

    missing = REQUIRED_KEYS - set(verdict.keys())
    if missing:
        print(f"Verdict missing keys: {missing}")
        return None

    return verdict


def find_existing_pr(repo, package_name: str) -> bool:
    """Check if an open Dependabot PR already bumps this package."""
    for pr in repo.get_pulls(state="open"):
        if pr.user.login != "dependabot[bot]":
            continue
        if package_name.lower() in pr.title.lower():
            print(f"  Existing PR #{pr.number}: {pr.title}")
            return True
    return False


def open_bump_pr(
    repo,
    alert_number: int,
    package_name: str,
    patched_version: str,
    ecosystem: str,
    dry_run: bool,
) -> None:
    """Create a branch and PR to bump the package to the patched version.

    This creates a minimal PR that updates the dependency specification.
    The actual file to modify depends on the ecosystem.
    """
    branch_name = f"blender/security/{alert_number}-{package_name}"
    default_branch = repo.default_branch
    title = f"fix(security): bump {package_name} to {patched_version}"
    body = (
        f"Bumps **{package_name}** to `{patched_version}` to resolve "
        f"Dependabot alert #{alert_number}.\n\n"
        f"BLEnder determined this vulnerability does not affect the "
        f"codebase, but the dependency should still be updated.\n\n"
        f"---\n"
        f"Generated by [BLEnder](https://github.com/mozilla/blender)."
    )

    if dry_run:
        print(f"  DRY_RUN: would create branch {branch_name}")
        print(f"  DRY_RUN: would open PR: {title}")
        return

    # Check if branch already exists
    try:
        repo.get_branch(branch_name)
        print(f"  Branch {branch_name} already exists, skipping.")
        return
    except Exception:
        pass

    # Create branch from default branch HEAD
    ref = repo.get_git_ref(f"heads/{default_branch}")
    repo.create_git_ref(f"refs/heads/{branch_name}", ref.object.sha)
    print(f"  Created branch {branch_name}")

    # Open PR (no file changes yet — Dependabot or CI will handle the bump)
    pr = repo.create_pull(
        title=title,
        body=body,
        head=branch_name,
        base=default_branch,
    )
    print(f"  Opened PR #{pr.number}: {title}")


def create_advisory_and_fork(
    repo,
    alert_number: int,
    package_name: str,
    dry_run: bool,
) -> tuple[str, str]:
    """Create a security advisory with a private fork.

    Returns (advisory_ghsa_id, fork_full_name) on success.
    """
    summary = f"Dependency security update for {package_name}"
    description = (
        f"Automated security update for Dependabot alert #{alert_number}. "
        f"See the advisory for details."
    )

    if dry_run:
        print(f"  DRY_RUN: would create advisory: {summary}")
        return ("", "")

    # Create advisory via raw API (PyGithub has no built-in method)
    url = f"/repos/{repo.full_name}/security-advisories"
    payload = {
        "summary": summary,
        "description": description,
        "severity": "low",
        "start_private_fork": True,
    }
    try:
        _, data = repo._requester.requestJsonAndCheck("POST", url, input=payload)
    except Exception as e:
        # Duplicate advisory returns 422
        error_str = str(e)
        if "422" in error_str or "already exists" in error_str.lower():
            print(f"  Advisory already exists for alert #{alert_number}, skipping.")
            return ("", "")
        raise

    ghsa_id = data.get("ghsa_id", "")
    print(f"  Created advisory {ghsa_id}")

    # Poll for private fork readiness (up to 5 minutes)
    fork_full_name = ""
    advisory_url = f"/repos/{repo.full_name}/security-advisories/{ghsa_id}"
    for attempt in range(10):
        time.sleep(min(30, 5 * (2**attempt)))
        _, advisory_data = repo._requester.requestJsonAndCheck("GET", advisory_url)
        forks = advisory_data.get("vulnerabilities", [])
        if forks:
            # The fork repo is in the advisory's fork field
            fork_info = advisory_data.get("private_fork", {})
            if fork_info:
                fork_full_name = fork_info.get("full_name", "")
                break
        # Also check top-level
        if advisory_data.get("private_fork"):
            fork_full_name = advisory_data["private_fork"].get("full_name", "")
            if fork_full_name:
                break

    if fork_full_name:
        print(f"  Private fork ready: {fork_full_name}")
    else:
        print("  Private fork not ready after polling. Remediate job may fail.")

    return (ghsa_id, fork_full_name)


SUMMARY_ISSUE_TITLE = "BLEnder: Dependabot alert investigation summary"
SUMMARY_TABLE_HEADER = (
    "| Alert | Package | Severity | Action | Reason |\n"
    "| ----- | ------- | -------- | ------ | ------ |"
)


def dismiss_alert(
    repo,
    alert_number: int,
    reason: str,
    dry_run: bool,
) -> None:
    """Dismiss a Dependabot alert as inaccurate (not affected)."""
    if dry_run:
        print(f"  DRY_RUN: would dismiss alert #{alert_number}")
        return

    url = f"/repos/{repo.full_name}/dependabot/alerts/{alert_number}"
    payload = {
        "state": "dismissed",
        "dismissed_reason": "inaccurate",
        "dismissed_comment": f"BLEnder: {reason}",
    }
    repo._requester.requestJsonAndCheck("PATCH", url, input=payload)
    print(f"  Dismissed alert #{alert_number}")


def post_summary_comment(
    repo,
    alert_number: int,
    package: str,
    severity: str,
    action: str,
    reason: str,
    dry_run: bool,
) -> None:
    """Post a row to the summary tracking issue.

    Creates the issue on first run. Each row is a comment to avoid
    read-modify-write races when many workflows run at once.
    """
    if dry_run:
        print("  DRY_RUN: would post summary comment")
        return

    # Find existing summary issue
    issues = repo.get_issues(state="open")
    summary_issue = None
    for issue in issues:
        if issue.title == SUMMARY_ISSUE_TITLE:
            summary_issue = issue
            break

    # Create issue if missing
    if summary_issue is None:
        summary_issue = repo.create_issue(
            title=SUMMARY_ISSUE_TITLE,
            body=(
                "BLEnder posts a comment here for each investigated "
                "Dependabot alert.\n\n" + SUMMARY_TABLE_HEADER
            ),
            labels=["blender"],
        )
        print(f"  Created summary issue #{summary_issue.number}")

    alert_url = (
        f"https://github.com/{repo.full_name}/security/dependabot/{alert_number}"
    )
    row = f"| [#{alert_number}]({alert_url}) | {package} | {severity} | {action} | {reason} |"
    summary_issue.create_comment(row)
    print(f"  Posted summary row to issue #{summary_issue.number}")


def main() -> None:
    token = os.environ.get("GH_TOKEN", "")
    repo_name = os.environ.get("REPO", "")
    alert_number = int(os.environ.get("ALERT_NUMBER", "0"))
    package_name = os.environ.get("ALERT_PACKAGE", "unknown")
    ecosystem = os.environ.get("ALERT_ECOSYSTEM", "unknown")
    severity = os.environ.get("ALERT_SEVERITY", "unknown")
    patched_version = os.environ.get("ALERT_PATCHED_VERSION", "")
    dry_run = os.environ.get("DRY_RUN", "false").lower() in ("true", "1", "yes")
    dismiss_enabled = os.environ.get("DISMISS_NOT_AFFECTED", "false").lower() in (
        "true",
        "1",
        "yes",
    )

    if not token or not repo_name:
        print("Error: GH_TOKEN and REPO are required.")
        sys.exit(1)

    if alert_number == 0:
        print("Error: ALERT_NUMBER is required.")
        sys.exit(1)

    g = Github(auth=Auth.Token(token))
    repo = g.get_repo(repo_name)

    verdict = load_verdict()
    if verdict is None:
        print("No valid verdict. Defaulting to no-op.")
        write_output("action", "noop")
        return

    affected = verdict.get("affected", False)
    recommended = verdict.get("recommended_action", "bump_pr")
    print(f"Verdict: affected={affected}, recommended={recommended}")
    print(f"  Reason: {verdict.get('reason', '(none)')}")

    reason = verdict.get("reason", "(none)")

    if not affected:
        if dismiss_enabled:
            print("  Not affected + dismiss enabled. Dismissing alert.")
            dismiss_alert(repo, alert_number, reason, dry_run)
            action = "dismissed"
        else:
            # Check for existing Dependabot PR
            has_pr = find_existing_pr(repo, package_name)

            if has_pr or recommended == "existing_pr":
                print("  Not affected + existing PR. No action needed.")
                action = "noop"
            else:
                print("  Not affected + no PR. Opening bump PR.")
                open_bump_pr(
                    repo,
                    alert_number,
                    package_name,
                    patched_version,
                    ecosystem,
                    dry_run,
                )
                action = "bump_pr"
        write_output("action", action)
    else:
        print("  Affected. Creating advisory and private fork.")
        ghsa_id, fork_repo = create_advisory_and_fork(
            repo,
            alert_number,
            package_name,
            dry_run,
        )
        action = "private_fork"
        write_output("action", action)
        write_output("advisory_ghsa_id", ghsa_id)
        write_output("fork_repo", fork_repo)

    post_summary_comment(
        repo, alert_number, package_name, severity, action, reason, dry_run
    )


def write_output(key: str, value: str) -> None:
    """Write a key=value pair to $GITHUB_OUTPUT."""
    output_file = os.environ.get("GITHUB_OUTPUT")
    if output_file:
        with open(output_file, "a") as f:
            f.write(f"{key}={value}\n")
    print(f"  output: {key}={value}")


if __name__ == "__main__":
    main()
